version: '3'
services:
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres-database
      - neo4j-database
  postgres-database:
    image: postgres
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  neo4j-database:
    image: neo4j:4.4-community
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/Neo4j
    volumes:
      - neo4j:/data

volumes:
  postgresdb:
  neo4j:
